// generated by stringer -output=strings.go -type=EventType,BinlogEventFlag,MariaGtidEventFlag; DO NOT EDIT

package binlog

import "fmt"

const (
	_EventType_name_0 = "UNKNOWN_EVENTSTART_EVENT_V3QUERY_EVENTSTOP_EVENTROTATE_EVENTINTVAR_EVENTLOAD_EVENTSLAVE_EVENTCREATE_FILE_EVENTAPPEND_BLOCK_EVENTEXEC_LOAD_EVENTDELETE_FILE_EVENTNEW_LOAD_EVENTRAND_EVENTUSER_VAR_EVENTFORMAT_DESCRIPTION_EVENTXID_EVENTBEGIN_LOAD_QUERY_EVENTEXECUTE_LOAD_QUERY_EVENTTABLE_MAP_EVENTWRITE_ROWS_EVENTv0UPDATE_ROWS_EVENTv0DELETE_ROWS_EVENTv0WRITE_ROWS_EVENTv1UPDATE_ROWS_EVENTv1DELETE_ROWS_EVENTv1INCIDENT_EVENTHEARTBEAT_EVENTIGNORABLE_EVENTROWS_QUERY_EVENTWRITE_ROWS_EVENTv2UPDATE_ROWS_EVENTv2DELETE_ROWS_EVENTv2GTID_EVENTANONYMOUS_GTID_EVENTPREVIOUS_GTIDS_EVENT"
	_EventType_name_1 = "MARIA_ANNOTATE_ROWS_EVENTMARIA_BINLOG_CHECKPOINT_EVENTMARIA_GTID_EVENTMARIA_GTID_LIST_EVENT"
)

var (
	_EventType_index_0 = [...]uint16{0, 13, 27, 38, 48, 60, 72, 82, 93, 110, 128, 143, 160, 174, 184, 198, 222, 231, 253, 277, 292, 310, 329, 348, 366, 385, 404, 418, 433, 448, 464, 482, 501, 520, 530, 550, 570}
	_EventType_index_1 = [...]uint8{0, 25, 54, 70, 91}
)

func (i EventType) String() string {
	switch {
	case 0 <= i && i <= 35:
		return _EventType_name_0[_EventType_index_0[i]:_EventType_index_0[i+1]]
	case 160 <= i && i <= 163:
		i -= 160
		return _EventType_name_1[_EventType_index_1[i]:_EventType_index_1[i+1]]
	default:
		return fmt.Sprintf("EventType(%d)", i)
	}
}

const (
	_BinlogEventFlag_name_0 = "LOG_EVENT_BINLOG_IN_USE_FLOG_EVENT_FORCED_ROTATE_F"
	_BinlogEventFlag_name_1 = "LOG_EVENT_THREAD_SPECIFIC_F"
	_BinlogEventFlag_name_2 = "LOG_EVENT_SUPPRESS_USE_FBinlogEventFlag"
	_BinlogEventFlag_name_3 = "LOG_EVENT_UPDATE_TABLE_MAP_VERSION_F"
	_BinlogEventFlag_name_4 = "LOG_EVENT_ARTIFICIAL_F"
	_BinlogEventFlag_name_5 = "LOG_EVENT_RELAY_LOG_F"
)

var (
	_BinlogEventFlag_index_0 = [...]uint8{0, 25, 50}
	_BinlogEventFlag_index_1 = [...]uint8{0, 27}
	_BinlogEventFlag_index_2 = [...]uint8{0, 39}
	_BinlogEventFlag_index_3 = [...]uint8{0, 36}
	_BinlogEventFlag_index_4 = [...]uint8{0, 22}
	_BinlogEventFlag_index_5 = [...]uint8{0, 21}
)

func (i BinlogEventFlag) String() string {
	switch {
	case 1 <= i && i <= 2:
		i -= 1
		return _BinlogEventFlag_name_0[_BinlogEventFlag_index_0[i]:_BinlogEventFlag_index_0[i+1]]
	case i == 4:
		return _BinlogEventFlag_name_1
	case i == 8:
		return _BinlogEventFlag_name_2
	case i == 16:
		return _BinlogEventFlag_name_3
	case i == 32:
		return _BinlogEventFlag_name_4
	case i == 64:
		return _BinlogEventFlag_name_5
	default:
		return fmt.Sprintf("BinlogEventFlag(%d)", i)
	}
}

const (
	_MariaGtidEventFlag_name_0 = "FL_STANDALONEFL_GROUP_COMMIT_ID"
	_MariaGtidEventFlag_name_1 = "FL_TRANSACTIONAL"
	_MariaGtidEventFlag_name_2 = "FL_ALLOW_PARALLEL"
	_MariaGtidEventFlag_name_3 = "FL_WAITED"
	_MariaGtidEventFlag_name_4 = "FL_DDL"
)

var (
	_MariaGtidEventFlag_index_0 = [...]uint8{0, 13, 31}
	_MariaGtidEventFlag_index_1 = [...]uint8{0, 16}
	_MariaGtidEventFlag_index_2 = [...]uint8{0, 17}
	_MariaGtidEventFlag_index_3 = [...]uint8{0, 9}
	_MariaGtidEventFlag_index_4 = [...]uint8{0, 6}
)

func (i MariaGtidEventFlag) String() string {
	switch {
	case 1 <= i && i <= 2:
		i -= 1
		return _MariaGtidEventFlag_name_0[_MariaGtidEventFlag_index_0[i]:_MariaGtidEventFlag_index_0[i+1]]
	case i == 4:
		return _MariaGtidEventFlag_name_1
	case i == 8:
		return _MariaGtidEventFlag_name_2
	case i == 16:
		return _MariaGtidEventFlag_name_3
	case i == 32:
		return _MariaGtidEventFlag_name_4
	default:
		return fmt.Sprintf("MariaGtidEventFlag(%d)", i)
	}
}
