// generated by stringer -output=strings.go -type=Capability,Status,Command; DO NOT EDIT

package proto

import "fmt"

const _Capability_name = "CLIENT_LONG_PASSWORDCLIENT_FOUND_ROWSCLIENT_LONG_FLAGCLIENT_CONNECT_WITH_DBCLIENT_NO_SCHEMACLIENT_COMPRESSCLIENT_ODBCCLIENT_LOCAL_FILESCLIENT_IGNORE_SPACECLIENT_PROTOCOL_41CLIENT_INTERACTIVECLIENT_SSLCLIENT_IGNORE_SIGPIPECLIENT_TRANSACTIONSCLIENT_RESERVEDCLIENT_SECURE_CONNECTIONCLIENT_MULTI_STATEMENTSCLIENT_MULTI_RESULTSCLIENT_PS_MULTI_RESULTSCLIENT_PLUGIN_AUTHCLIENT_CONNECT_ATTRSCLIENT_PLUGIN_AUTH_LENENC_CLIENT_DATACLIENT_CAN_HANDLE_EXPIRED_PASSWORDSCLIENT_SSL_VERIFY_SERVER_CERTCLIENT_DEPRECATE_EOFCLIENT_REMEMBER_OPTIONSCLIENT_BASIC_FLAGSCLIENT_ALL_FLAGS"

var _Capability_map = map[Capability]string{
	1:          _Capability_name[0:20],
	2:          _Capability_name[20:37],
	4:          _Capability_name[37:53],
	8:          _Capability_name[53:75],
	16:         _Capability_name[75:91],
	32:         _Capability_name[91:106],
	64:         _Capability_name[106:117],
	128:        _Capability_name[117:135],
	256:        _Capability_name[135:154],
	512:        _Capability_name[154:172],
	1024:       _Capability_name[172:190],
	2048:       _Capability_name[190:200],
	4096:       _Capability_name[200:221],
	8192:       _Capability_name[221:240],
	16384:      _Capability_name[240:255],
	32768:      _Capability_name[255:279],
	65536:      _Capability_name[279:302],
	131072:     _Capability_name[302:322],
	262144:     _Capability_name[322:345],
	524288:     _Capability_name[345:363],
	1048576:    _Capability_name[363:383],
	2097152:    _Capability_name[383:420],
	4194304:    _Capability_name[420:455],
	8388608:    _Capability_name[455:484],
	16777216:   _Capability_name[484:504],
	2147483648: _Capability_name[504:527],
	2155870175: _Capability_name[527:545],
	2164260863: _Capability_name[545:561],
}

func (i Capability) String() string {
	if str, ok := _Capability_map[i]; ok {
		return str
	}
	return fmt.Sprintf("Capability(%d)", i)
}

const (
	_Status_name_0 = "SERVER_STATUS_IN_TRANS"
	_Status_name_1 = "SERVER_STATUS_CLEAR_SET"
)

var (
	_Status_index_0 = [...]uint8{0, 22}
	_Status_index_1 = [...]uint8{0, 23}
)

func (i Status) String() string {
	switch {
	case i == 1:
		return _Status_name_0
	case i == 3576:
		return _Status_name_1
	default:
		return fmt.Sprintf("Status(%d)", i)
	}
}

const _Command_name = "COM_SLEEPCOM_QUITCOM_INIT_DBCOM_QUERYCOM_FIELD_LISTCOM_CREATE_DBCOM_DROP_DBCOM_REFRESHCOM_SHUTDOWNCOM_STATISTICSCOM_PROCESS_INFOCOM_CONNECTCOM_PROCESS_KILLCOM_DEBUGCOM_PINGCOM_TIMECOM_DELAYED_INSERTCOM_CHANGE_USERCOM_BINLOG_DUMPCOM_TABLE_DUMPCOM_CONNECT_OUTCOM_REGISTER_SLAVECOM_STMT_PREPARECOM_STMT_EXECUTECOM_STMT_SEND_LONG_DATACOM_STMT_CLOSECOM_STMT_RESETCOM_SET_OPTIONCOM_STMT_FETCHCOM_DAEMONCOM_BINLOG_DUMP_GTIDCOM_RESET_CONNECTION"

var _Command_index = [...]uint16{0, 9, 17, 28, 37, 51, 64, 75, 86, 98, 112, 128, 139, 155, 164, 172, 180, 198, 213, 228, 242, 257, 275, 291, 307, 330, 344, 358, 372, 386, 396, 416, 436}

func (i Command) String() string {
	if i >= Command(len(_Command_index)-1) {
		return fmt.Sprintf("Command(%d)", i)
	}
	return _Command_name[_Command_index[i]:_Command_index[i+1]]
}
